### PR TITLE
Add IsModularLatticeDigraph

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
@MTWhyte is going to take this to completion

**Comment by james-d-mitchell** [comment]
@MTWhyte I've just rebased this on to `main` which will hopefully fix the ci, I had to force push, which might interact badly if you've already been working on this. Please let me know if you need any help

**Comment by MTWhyte** [comment]
> @MTWhyte I've just rebased this on to `main` which will hopefully fix the ci, I had to force push, which might interact badly if you've already been working on this. Please let me know if you need any help

Cool yeah I've started on it, I'll see how it goes when I rebase

**Review by james-d-mitchell — COMMENTED** [review]
I approve, but can't approve because I'm the author, oh well

**Comment by james-d-mitchell** [comment]
Thanks @MTWhyte !

**Pull request merged**
