### PR TITLE
Remove links to gap-packages/Digraphs

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Review by wilfwilson — DISMISSED** [review]

**Comment by wilfwilson** [comment]
I think this should also be to the `stable-1.3` branch. That way you'll get the linting CI to run, too.

**Comment by alex-konovalov** [comment]
Please remember to let me know when you will publish a release from a new location, to update check for new package releases!

**Comment by alex-konovalov** [comment]
P.S. https://github.com/gap-packages/gap-packages.github.io/blob/master/index.md needs updating - it lists packages outside gap-packages organisation explicitly. Please do this, so that visitors can find new websites!

**Comment by wilfwilson** [comment]
> P.S. https://github.com/gap-packages/gap-packages.github.io/blob/master/index.md needs updating - it lists packages outside gap-packages organisation explicitly. Please do this, so that visitors can find new websites!

I made a PR to do this https://github.com/gap-packages/gap-packages.github.io/pull/11

**Review by wilfwilson — APPROVED** [review]

**Pull request merged**
