### PR TITLE
Rewrite buildsystem to use Makefile.gappkg

### PR DESCRIPTION
**Pull request by fingolfin**
This should remove the problems on OpenBSD (see issue #562, CC @dimpase), and speed up build times.

I have done some limited testing on macOS and Linux. Before I spend more time on polish, I'll wait to hear if there is any interest in this (plus CI results will of course be interesting).

### CODE REVIEW

**Comment by dimpase** [comment]
Thanks! I'll test on OpenBSD and report.

**Comment by james-d-mitchell** [comment]
Just to say that @fingolfin and I discussed this today, and I'll be happy to merge this when you tell me you're done @fingolfin. Many thanks!

**Comment by dimpase** [comment]
should this be tested on GAP master, or on another branch?

**Comment by fingolfin** [comment]
@dimpase whichever is handy for you (and of course the OpenBSD problem should manifest, I don't know whether you tested this with multiple GAP versions)

**Comment by fingolfin** [comment]
@james-d-mitchell from my POV this is done but perhaps we wait and see what @dimpase reports?

**Comment by james-d-mitchell** [comment]
Excellent thanks very much @fingolfin ! I'll wait to hear the last word from @dimpase, then merge

**Comment by dimpase** [comment]
> @dimpase out of curiosity, what does `file bin/*/digraphs.so` say with this PR versus with `main`?

it says `ELF 64-bit LSB shared object, x86-64, version 1` (same as for broken `semigroups.so`)
More interesting is what `ldd` says:
```
$ ldd bin/x86_64-unknown-openbsd7.1-default64-kv8/digraphs.so  
bin/x86_64-unknown-openbsd7.1-default64-kv8/digraphs.so:
        Start            End              Type  Open Ref GrpRef Name
        000001b09ef72000 000001b09f005000 dlib  2    0   0      /home/dima/tmp/gap/pkg/digraphs/bin/x86_64-unknown-openbsd7.1-default64-kv8/digraphs.so
        000001b060da8000 000001b060e8c000 rlib  0    1   0      /usr/lib/libc++.so.9.0
        000001b02581b000 000001b025861000 rlib  0    2   0      /usr/lib/libc++abi.so.6.0
        000001b057206000 000001b057212000 rlib  0    1   0      /usr/lib/libpthread.so.26.1
```
whereas for `semigroups.so` it's an error:
```
$ ldd bin/x86_64-unknown-openbsd7.1-default64-kv8/semigroups.so                                                                                      
bin/x86_64-unknown-openbsd7.1-default64-kv8/semigroups.so:
Cannot load specified object
bin/x86_64-unknown-openbsd7.1-default64-kv8/semigroups.so: exit status 1
$ file bin/x86_64-unknown-openbsd7.1-default64-kv8/semigroups.so 
bin/x86_64-unknown-openbsd7.1-default64-kv8/semigroups.so: ELF 64-bit LSB shared object, x86-64, version 1
```

**Comment by dimpase** [comment]
> Excellent thanks very much @fingolfin ! I'll wait to hear the last word from @dimpase, then merge

it's a big OK from me.

**Pull request merged**
