### PR TITLE
kernel: fix check in OutNeighbours

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This PR fixes Issue #518.

### CODE REVIEW

**Review by wilfwilson — APPROVED** [review]
Cheers

**Comment by james-d-mitchell** [comment]
The CI fails because of some issues with the wording of errors, any idea how I can add this test and get around this @wilfwilson ?
~~~~
Error, expected a digraph, not a homogeneous plain list
Error, expected a digraph, not a list (plain,hom)
~~~~

**Comment by wilfwilson** [comment]
I've pushed a slightly different test, I hope you don't mind. If you do `OutNeighbours(OutNeighbours)` then you get a consistent error message across GAP versions:
```
Error, expected a digraph, not a function
```
Once we require GAP 4.11, these kinds of problems will be straightforward to work around because you can use the syntax `#@if`, `#@else`, and `#@endif` in test files to test stuff conditionally, and to expect different outputs.

**Comment by james-d-mitchell** [comment]
> I've pushed a slightly different test, I hope you don't mind.

Thanks! 

> Once we require GAP 4.11, these kinds of problems will be straightforward to work around because you can use the syntax `#@if`, `#@else`, and `#@endif` in test files to test stuff conditionally, and to expect different outputs.

I didn't know this! Awesome!

**Pull request merged**
