### PR TITLE
Added IsOrderFilter

### PR DESCRIPTION
**Pull request by zljlzljlz**
#522 - returns true if the specified subset is upwards closed, false if not, based on IsOrderIdeal.

### CODE REVIEW

**Comment by mtorpey** [comment]
I took a look at this and offered @zljlzljlz some pointers.  She made a lot of progress, which should hopefully be pushed soon.

**Comment by james-d-mitchell** [comment]
Thanks both, I look forward to seeing this when pushed 👍

**Comment by mtorpey** [comment]
It looks like `doc/title.xml` was added to the repo accidentally.  Could you remove this?

Otherwise, this is looking good – I'd recommend merging after that change.

**Comment by james-d-mitchell** [comment]
Agreed I'll be happy to merge when the `title.xml` file is removed. Thanks @zljlzljlz !

**Review by mtorpey — APPROVED** [review]
Great

**Pull request merged**
