### PR TITLE
Add checks for upper/lower semimodular lattices

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
This should be good to go. If @reiniscirpons or @wilfwilson could give it a look over, I'd be most grateful.

**Review by wilfwilson — APPROVED** [review]
Implementation looks good, just got a couple of suggestions for the doc.

**Comment by james-d-mitchell** [comment]
Thanks @wilfwilson, I agree with all of your comments!

**Comment by wilfwilson** [comment]
Something weird happened with the GitHub Actions macOS job (it failed to compile the profiling package), I propose that we ignore it and not waste the time re-running the tests. It can't be related to this PR, and macOS jobs are running fine on other PRs.

**Pull request merged**
